### PR TITLE
Add observability-bundle

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Towards https://github.com/giantswarm/giantswarm/issues/24246

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Did you have time to test?

**Comment by mcbenjemaa** [comment]
Not Yet!

**Review by fiunchinho — APPROVED** [review]

**Comment by mcbenjemaa** [comment]
@giantswarm/team-hydra Do we have to release this?

**Comment by fiunchinho** [comment]
Yes. And if you want current MCs to use it, they need to be upgraded to this version.

**Comment by QuentinBisson** [comment]
@fiunchinho doers this also apply to cluster-aws?

**Comment by QuentinBisson** [comment]
@mcbenjemaa can you take care of the release? :)

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
