### PR TITLE
Enable renovate to update app versions

### PR DESCRIPTION
**Pull request by erkanerol**
### What this PR does / why we need it

Towards https://github.com/giantswarm/giantswarm/issues/23311
Similar to https://github.com/giantswarm/default-apps-openstack/pull/66

### CODE REVIEW

**Review by calvix — APPROVED** [review]
lgtm

**Review by fiunchinho — COMMENTED** [review]
won't this configuration be overwritten next time our `giantswarm/github` automation kicks in?

**Comment by erkanerol** [comment]
@fiunchinho Is this PR also necessary? https://github.com/giantswarm/github/pull/618/files

**Comment by fiunchinho** [comment]
> @fiunchinho Is this PR also necessary? https://github.com/giantswarm/github/pull/618/files

I think so. I think our automation manages the renovate file so it would overwrite the changes on this PR. That's what I think at least, I'm not 100% sure.

**Pull request merged**
