### PR TITLE
Explicitly define apps configmaps so we can use helm values on them

### PR DESCRIPTION
**Pull request by fiunchinho**
### What this PR does / why we need it

We need to pass dynamic values to the configmaps created for the default apps. So instead of defining the configmaps in the `values.yaml` file, we define them in a template. That way we can access to the values passed when installing this app.

### Checklist

- [X] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create

### CODE REVIEW

**Comment by fiunchinho** [comment]
[CAPI introduced a field](https://github.com/kubernetes-sigs/cluster-api/pull/5993) that can be used to tell `kubeadm` to _skip_ a phase, like skip installing `kube-proxy. This is available on CAPI 1.2.x, but we are not using that version just yet. [We have a PR open to upgrade it](https://github.com/giantswarm/cluster-api-app/pull/90) but we need to be careful because not all CAPI providers are compatible with CAPI 1.2.x yet.

**Review by calvix — APPROVED** [review]

**Comment by calvix** [comment]
should we do the same for CAPA?

**Comment by fiunchinho** [comment]
> should we do the same for CAPA?

Yes, I'd use the same approach for all default apps bundles on all providers.

**Comment by fiunchinho** [comment]
The e2e tests will fail until [this is released](https://github.com/giantswarm/kubectl-gs/pull/906) and used in the tests.

**Pull request merged**
