### PR TITLE
Update node-exporter to 1.15.0

### PR DESCRIPTION
**Pull request by marieroque**
Towards https://github.com/giantswarm/node-exporter-app/issues/172

### CODE REVIEW

**Review by mcbenjemaa — APPROVED** [review]

**Review by calvix — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]

**Comment by fiunchinho** [comment]
@marieroque Normally we wait until all the checks are green, it seems that the `create` test was still running

image

**Comment by QuentinBisson** [comment]
@marieroque  can you add this to the new documetnation about releases? Maybe also the / test commands :)

**Comment by fiunchinho** [comment]
This is not really about releases though. We run these tests on every PR. Maybe we can improve the pull request template somehow? https://raw.githubusercontent.com/giantswarm/default-apps-gcp/main/.github/pull_request_template.md

**Pull request merged**
